### ISSUE TITLE
Application Development Roadmap

### ISSUE THREAD

**Issue by micahbule** [DelRosarioEldrinRei/You-re-Somebody-s-Type#1]
## Minimum Viable Product (MVP)
For you final project, I would be requiring you to develop the following features based on the [list](https://github.com/DelRosarioEldrinRei/Youre-Somebodys-Type/blob/master/You're%20Somebody's%20Type%20Features.docx) you pushed in this repository:

- [ ] User login for all three types of users (Admin, Blood Bank, Member)
- [ ] As an admin, a user should be able to create an account for a blood bank
- [ ] As a blood bank (representative), a user should be able to update information about the blood bank reserves (? - what type of blood and related components are available at any given point of time)
- [ ] As a member, a user should be able to post a request for any blood type or component
- [ ] As a member, a user should be able to view & respond to blood type or component requests

## Next Critical Features
The following features are critical for your application such that after the MVP, these would be the next necessary features to be developed:

- [ ] As a blood bank (representative), a user should be able to post events such as blood letting
- [ ] User profiles for members
- [ ] Messaging (real-time if possible)
- [ ] As I understood from our last checkpoint, you are not planning to include an interactive map, so that's also a critical feature

## Nice-2-Haves (N2Hs)
These features are not that necessary for your application to run smoothly, but they are definitely nice to have if you can throw them in:

- [ ] User ban and reinstate features

## Unmentioned feature?
Any other features in your list not mentioned in this issue are either vague or is left for the developers to decide whether to include it or not.
